project_name: 'geoipupdate'
archives:
  - id: main
    wrap_in_directory: true
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'
      - 'GeoIP.conf'
      - 'GeoIP.conf.md'
      - 'geoipupdate.md'
builds:
  - main: './cmd/geoipupdate'
    binary: 'geoipupdate'
    goarch:
      - '386'
      - 'amd64'
      - 'arm'
      - 'arm64'
    goos:
      - 'darwin'
      - 'linux'
    hooks:
      post: 'make data BUILDDIR=.'
    env:
      - CGO_ENABLED=0
dockers:
  - image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
    dockerfile: docker/Dockerfile
    goarch: amd64
    extra_files:
      - docker/entry.sh
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
    dockerfile: docker/Dockerfile
    goarch: arm64
    extra_files:
      - docker/entry.sh
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "maxmindinc/geoipupdate:{{ .Tag }}"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
  - name_template: "maxmindinc/geoipupdate:v{{ .Major }}"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
  - name_template: "maxmindinc/geoipupdate:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
  - name_template: "maxmindinc/geoipupdate:latest"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
checksum:
  name_template: 'checksums-darwin-linux.txt'
