project_name: 'geoipupdate'
archives:
  - id: main
    wrap_in_directory: true
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'
      - 'GeoIP.conf'
      - 'GeoIP.conf.md'
      - 'geoipupdate.md'
builds:
  - main: './cmd/geoipupdate'
    binary: 'geoipupdate'
    goos:
      - 'darwin'
      - 'linux'
      - 'freebsd'
    goarch:
      - '386'
      - 'amd64'
      - 'arm'
      - 'arm64'
      - 'ppc64le'
      - 's390x'
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: 'freebsd'
        goarch: 'arm'
      - goos: 'freebsd'
        goarch: 'arm64'
    hooks:
      post: 'make data BUILDDIR=.'
checksum:
  name_template: 'checksums-darwin-linux.txt'
