project_name: 'geoipupdate'
archives:
  - id: main
    wrap_in_directory: true
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'
      - 'GeoIP.conf'
      - 'GeoIP.conf.md'
      - 'geoipupdate.md'
    format_overrides:
      - goos: windows
        format: zip
builds:
  - main: './cmd/geoipupdate'
    binary: 'geoipupdate'
    goarch:
      - '386'
      - 'amd64'
      - 'arm'
      - 'arm64'
    goos:
      - 'darwin'
      - 'linux'
      - 'freebsd'
      - 'openbsd'
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
    hooks:
      post: 'make data BUILDDIR=.'
    env:
      - CGO_ENABLED=0
  - id: 'geoipupdate-windows'
    main: './cmd/geoipupdate'
    binary: 'geoipupdate'
    goarch:
      - '386'
      - 'amd64'
    goos:
      - 'windows'
    hooks:
      post: 'make data OS=Windows_NT BUILDDIR=.'
    env:
      - CGO_ENABLED=0
dockers:
  - image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
    dockerfile: docker/Dockerfile
    use: buildx
    goarch: amd64
    extra_files:
      - docker/entry.sh
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
    dockerfile: docker/Dockerfile
    use: buildx
    goarch: arm64
    extra_files:
      - docker/entry.sh
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm-v6"
    dockerfile: docker/Dockerfile
    use: buildx
    goarch: arm
    goarm: 6
    extra_files:
      - docker/entry.sh
    build_flag_templates:
      - "--platform=linux/arm/v6"
docker_manifests:
  - name_template: "maxmindinc/geoipupdate:{{ .Tag }}"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm-v6"
  - name_template: "maxmindinc/geoipupdate:v{{ .Major }}"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm-v6"
  - name_template: "maxmindinc/geoipupdate:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm-v6"
  - name_template: "maxmindinc/geoipupdate:latest"
    image_templates:
      - "maxmindinc/geoipupdate:{{ .Tag }}-amd64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm64"
      - "maxmindinc/geoipupdate:{{ .Tag }}-arm-v6"
checksum:
  name_template: 'checksums-darwin-linux.txt'
