[settings]
lockfile = true
disable_backends = [
    "asdf",
    "vfox",
]

[tools]
go = "latest"
"github:golangci/golangci-lint" = "latest"
"github:houseabsolute/precious" = "latest"

[hooks]
enter = "mise install --quiet"

[[watch_files]]
patterns = ["mise.toml", "mise.lock"]
run = "mise install --quiet"
