name: Check Untagged Dependencies

on:
  push:
  pull_request:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: horgh/check-untagged-go-deps@1e727f9fffc10de1d5db85032c02e17081077602 # v1.1.0
