name: modver

on:
  pull_request:

permissions:
  contents: read # This gets granted by default, so keep granting it.
  packages: read # This gets granted by default, so keep granting it.
  pull-requests: write # Needed to comment on the PR.

jobs:
  modver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: bobg/modver@4ef2be8b32c8428acd7b6783d459c6e3b8767d8c # v2.14.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_url: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
